name: Build, Test, and Deploy for Development

on:
  push:
    branches:
      - dev

jobs:
  build_and_upload_artifact:
    runs-on: ubuntu-latest
    environment: development
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"
      - name: Build the application
        run: go build -o development_app

      - name: Copy artifacts to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          port: ${{ env.SSH_PORT }}
          source: "development_app"
          target: ~/golang/backend

  restart_app:
    runs-on: ubuntu-latest
    needs: build_and_upload_artifact
    environment: development
    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          port: ${{ env.SSH_PORT }}
          script: |
            mkdir -p ~/golang/backend
            cd ~/golang/backend
            git reset --hard
            git pull origin dev
            pm2 stop development_app
            pm2 start development_app
